# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/riscv32KC2.xdc

# IP: ip/riscv32KC2_fpga_pll/riscv32KC2_fpga_pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv32KC2_fpga_pll || ORIG_REF_NAME==riscv32KC2_fpga_pll} -quiet] -quiet
