# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "F:/Work/risv32KC2/hdl/fpga/riscv32KC2.runs/synth_1/riscv32KC2_fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Work/risv32KC2/hdl/fpga/riscv32KC2.cache/wt [current_project]
set_property parent.project_path F:/Work/risv32KC2/hdl/fpga/riscv32KC2.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/Work/risv32KC2/hdl/fpga/riscv32KC2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  F:/Work/risv32KC2/hdl/rtl/bus/apb_decoder.v
  F:/Work/risv32KC2/hdl/rtl/peripheral/gpio/apb_gpio.v
  F:/Work/risv32KC2/hdl/rtl/peripheral/uart/apb_uart.v
  F:/Work/risv32KC2/hdl/rtl/bus/axi2apb_bridge.v
  F:/Work/risv32KC2/hdl/rtl/bus/axi_fifo.v
  F:/Work/risv32KC2/hdl/rtl/bus/axi_lite_demux.v
  F:/Work/risv32KC2/hdl/rtl/bus/axi_lite_mux2.v
  F:/Work/risv32KC2/hdl/rtl/clint/axi_riscv_clint.v
  F:/Work/risv32KC2/hdl/rtl/plic/axi_riscv_plic.v
  F:/Work/risv32KC2/hdl/rtl/bus/axi_slv_to_dev_inf.v
  F:/Work/risv32KC2/hdl/rtl/misc/booth_mult_r4_b.v
  F:/Work/risv32KC2/hdl/rtl/misc/buf_cdc_rx.v
  F:/Work/risv32KC2/hdl/rtl/misc/buf_cdc_tx.v
  F:/Work/risv32KC2/hdl/rtl/debug_module/debug_rom_013.v
  F:/Work/risv32KC2/hdl/rtl/misc/div_r4.v
  F:/Work/risv32KC2/hdl/rtl/debug_module/dm_mem.v
  F:/Work/risv32KC2/hdl/rtl/peripheral/gpio/gpio.v
  F:/Work/risv32KC2/hdl/rtl/ram/mrom.v
  F:/Work/risv32KC2/hdl/rtl/ram/mrom_axi_lite.v
  F:/Work/risv32KC2/hdl/rtl/misc/ram_model.v
  F:/Work/risv32KC2/hdl/rtl/bus/read_req_to_axi.v
  F:/Work/risv32KC2/hdl/rtl/bus/riscv32KC2_bus.v
  F:/Work/risv32KC2/hdl/rtl/peripheral/riscv32KC2_peripheral.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_defines.v
  F:/Work/risv32KC2/hdl/rtl/riscv32KC2_system/riscv32KC2_system.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_alu.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_axi_data.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_axi_ifetch.v
  F:/Work/risv32KC2/hdl/rtl/clint/riscv_clint.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_core.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_csr.v
  F:/Work/risv32KC2/hdl/rtl/debug_module/riscv_debug_block.v
  F:/Work/risv32KC2/hdl/rtl/debug_module/riscv_debug_module.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_decode.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_decoder.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_exu.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_fetch_pc_unit.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_final_stage.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_if_stage.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_iram_arbit.v
  F:/Work/risv32KC2/hdl/rtl/debug_module/riscv_jtag_dtm.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_mem.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_multdiv.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_pipeline.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_pipeline_regs.v
  F:/Work/risv32KC2/hdl/rtl/plic/riscv_plic.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_regfile.v
  F:/Work/risv32KC2/hdl/rtl/riscv_core/riscv_wb.v
  F:/Work/risv32KC2/hdl/rtl/misc/sync_fifo.v
  F:/Work/risv32KC2/hdl/rtl/bus/write_req_to_axi.v
  F:/Work/risv32KC2/hdl/rtl/riscv32KC2_system/riscv32KC2_fpga.v
}
read_ip -quiet F:/Work/risv32KC2/hdl/fpga/riscv32KC2.srcs/sources_1/ip/riscv32KC2_fpga_pll/riscv32KC2_fpga_pll.xci
set_property used_in_implementation false [get_files -all f:/Work/risv32KC2/hdl/fpga/riscv32KC2.gen/sources_1/ip/riscv32KC2_fpga_pll_1/riscv32KC2_fpga_pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/Work/risv32KC2/hdl/fpga/riscv32KC2.gen/sources_1/ip/riscv32KC2_fpga_pll_1/riscv32KC2_fpga_pll.xdc]
set_property used_in_implementation false [get_files -all f:/Work/risv32KC2/hdl/fpga/riscv32KC2.gen/sources_1/ip/riscv32KC2_fpga_pll_1/riscv32KC2_fpga_pll_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Work/risv32KC2/hdl/fpga/riscv32KC2.srcs/constrs_1/new/riscv32KC2.xdc
set_property used_in_implementation false [get_files F:/Work/risv32KC2/hdl/fpga/riscv32KC2.srcs/constrs_1/new/riscv32KC2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental F:/Work/risv32KC2/hdl/fpga/riscv32KC2.srcs/utils_1/imports/synth_1/riscv32KC2_fpga.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top riscv32KC2_fpga -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv32KC2_fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file riscv32KC2_fpga_utilization_synth.rpt -pb riscv32KC2_fpga_utilization_synth.pb" "report_timing -setup -file synth_report_timing_0.rpt -rpx synth_report_timing_0.rpx"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
