onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_riscv32KC2_system/u_system/uart_txd
add wave -noupdate /tb_riscv32KC2_system/u_system/uart_rxd
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/if_pc
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/if_instruction
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/if_valid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/completed_pc
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/completed_instruction
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/id_valid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/nstage_ready
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/valid_instr
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/valid_exe
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/instruction_complete
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/flush
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/data_i
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/vld_i
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/rdy_o
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/empty
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/rdy_i
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/data_o
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/vld_o
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/nstage_ready
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/id_pc
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/id_instruction
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/id_valid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_id_regs/flush
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/mem_pending
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/if_id_valid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/ctrl_reg_we
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/ctrl_reg_src
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/ctrl_mem_req
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/ctrl_mem_we
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/s_wait_rvalid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/pipeline_stall
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/clint_tmr_irq
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/clint_sft_irq
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_wb/u_regfile/t0
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_wb/u_regfile/t1
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_wb/u_regfile/a0
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_wb/u_regfile/a1
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_wb/u_regfile/a2
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/mem_req
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/mem_we
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/mem_addr
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/mem_wdata
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/mem_be
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/mem_rdata
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/mem_ready
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/mem_rvalid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/write_axi_ready
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_data/read_axi_ready
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_decode/u_decoder/instruction
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_decode/u_decoder/pc
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_decode/u_decoder/mem_req
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_decode/u_decoder/mem_we
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_decode/u_decoder/illegal_inst
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_decode/u_decoder/compressed_valid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/ctrl_mem_req
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/ctrl_mem_we
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/mem_req
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/s_wait_rvalid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/mem_ready
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/mem_rvalid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/mem_rd_req
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_final_stage/u_mem/mem_wr_req
add wave -noupdate /tb_riscv32KC2_system/sys_clk
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_dram_sram/mem
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/s_fetch_state
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/s_instr_state
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/pc_update
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/buf_instr
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/ifetch_rvalid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/ifu_ready
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/instr_rvalid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/next_pc
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/pc
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/fetch_addr
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/instr_i
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/instr_o
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/fetch_done
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/buf_rdy
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/buf_pop
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/pc1_sel
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/flush
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/u_fetch_pc/skip_instr_rvalid
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/debug_mode_pc
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/dret_taken
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/mret_taken
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/trap_taken
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/trap_vector
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/jump_target
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/early_jump_wrong_addr
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/early_jump_wrong_taken
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/early_not_jump_need_jump
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/early_jalr_target_base
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/early_jal_target
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/early_jalr_target
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/early_branch_target
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/next_pc1
add wave -noupdate /tb_riscv32KC2_system/u_system/u_riscv_core/u_pipeline/u_if_stage/if_restore_mis_target
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {10712500 ps} 0} {{Cursor 2} {10737881 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 625
configure wave -valuecolwidth 204
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {9898117 ps} {11717225 ps}

